# Generated by Django 5.0.4 on 2024-04-07 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_messages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
    ]
