# Generated by Django 5.0.3 on 2024-03-14 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_tags_project_vote_ratio_project_vote_total_review_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tags',
            new_name='Tag',
        ),
    ]
